spring:
  application:
    name: planoramaweb
  datasource:
    url: jdbc:h2:file:./data/planoramaweb
    driver-class-name: org.h2.Driver
    username: user
    password: passwd
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
server:
  port: 8081